# Generated by Django 3.0.4 on 2020-04-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=256)),
                ('version', models.CharField(max_length=256)),
            ],
        ),
    ]
