# Generated by Django 3.0.4 on 2020-04-01 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributeIdForeignKey', models.IntegerField()),
                ('tableIdForeign', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('databaseName', models.CharField(max_length=256)),
                ('tablesCount', models.IntegerField()),
                ('datasourceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Datasource')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tableName', models.CharField(max_length=256)),
                ('columnCount', models.IntegerField()),
                ('datasourceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Datasource')),
                ('schemaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Schema')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('columnName', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=256)),
                ('nullable', models.BooleanField()),
                ('key', models.CharField(max_length=256)),
                ('datasourceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Datasource')),
                ('schemaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Schema')),
                ('tableId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Table')),
            ],
        ),
    ]
