# Generated by Django 3.0.4 on 2020-04-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_attribute_mapping_schema_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='key',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
